### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by moulid15** [UB-CSE/course-project-sayless#1]
As a person with their own personal devices , I want to the website to be deployed to a web server, so that I can access it from my own machine.

Acceptance Test:

Simply navigate to http://sayless.azurewebsites.net/login and confirm that the website is accessible and functional from your own machine. This should include registering, logging in,  searching for a user by username, and basic chat functionality. This also means the register page, login page, profile page, homepage and chat page should accessible.

**Comment by Shazmaan** [comment]
Moulid is moe
