### ISSUE TITLE
Login GUI Template

### ISSUE THREAD

**Issue by dannyb-421** [UB-CSE/course-project-sayless#20]
Make the design for the login page and show with a wireframe. Research tools/languages to build the UI of this application, document, and report back to group with a plan

Test:

1. Have a clear design/wireframe to present to the group
2. Have a basic understanding a be able to report to group the languages/tools you plan to use

![Login Wireframe.png](https://images.zenhubusercontent.com/5f5423d1dbcfc63140b4c490/3997fc38-6e24-4154-afaa-f87e3511fdbc)

**Comment by rileyb123** [comment]
Test:

1. Have a clear design/wireframe to present to the group
2. Have a basic understanding a be able to report to group the languages/tools you plan to use

**Comment by rileyb123** [comment]
Test:

1. Have a clear design/wireframe to present to the group
2. Have a basic understanding a be able to report to group the languages/tools you plan to use
