### ISSUE TITLE
Reading Messages

### ISSUE THREAD

**Issue by dannyb-421** [UB-CSE/course-project-sayless#50]
User is able to see messages in chat with another user.

These are the task tests for chat: (test_chat.py) [#62](https://app.zenhub.com/workspaces/sayless-5f5422b28f5c0300138a0f74/issues/ub-cse/course-project-sayless/62)

test0 : test if chat renders for client1
test1 : test if chat renders for client2
test2 : test if redirected to login page for invalid sign in

**Comment by Shazmaan** [comment]
https://app.zenhub.com/workspaces/sayless-5f5422b28f5c0300138a0f74/issues/ub-cse/course-project-sayless/62 for all tests
