### ISSUE TITLE
HomePage Functionality

### ISSUE THREAD

**Issue by dannyb-421** [UB-CSE/course-project-sayless#61]
Add Functionalities desired for homepage features. This includes open chats area, suggested chats, user bio section, log out, and moving chats onto the homepage.

Task Test:

Following will be tested through either frontend or backend tests or both, depending on the nature of the task.

1) Users can see the chats they have open currently.
2) On the left, users can see a list of their open chats and a list of suggested chats. This enables users to start a new chat with users without searching them.
3) Users can search other users by using the search bar above the chats.
4) Users are not required to search a user they have an existing chat with to reopen the chat.
5) User can log out of their account by clicking on the logout button on the upper right corner in the homepage screen.
6) Logged in user can see account information (name, bio and picture placeholder) on the right hand side.

**Comment by shreyala** [comment]
Combine chat and homepage wireframe.
Essentially following the wireframe:
1. Shows up on the same page.
2. It looks like how you want it to look.
